// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0wmkNpFB0R0ANjYkPW40lImyrPJNGIQ',
    appId: '1:358582698343:web:4dfef0b0748d0e5910efc2',
    messagingSenderId: '358582698343',
    projectId: 'safespace-chattingapp',
    authDomain: 'safespace-chattingapp.firebaseapp.com',
    storageBucket: 'safespace-chattingapp.firebasestorage.app',
    measurementId: 'G-MEE3PY8M86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkNqByJuB02sIuYmuNgGQTW9VxulhSzM',
    appId: '1:358582698343:android:0ef529d8a84f336010efc2',
    messagingSenderId: '358582698343',
    projectId: 'safespace-chattingapp',
    storageBucket: 'safespace-chattingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmMKkZM188XspVQFyT6zIlvWnPIyU5ts',
    appId: '1:358582698343:ios:6076113453ff95c910efc2',
    messagingSenderId: '358582698343',
    projectId: 'safespace-chattingapp',
    storageBucket: 'safespace-chattingapp.firebasestorage.app',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOmMKkZM188XspVQFyT6zIlvWnPIyU5ts',
    appId: '1:358582698343:ios:6076113453ff95c910efc2',
    messagingSenderId: '358582698343',
    projectId: 'safespace-chattingapp',
    storageBucket: 'safespace-chattingapp.firebasestorage.app',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl0wmkNpFB0R0ANjYkPW40lImyrPJNGIQ',
    appId: '1:358582698343:web:cba7be12f5300ded10efc2',
    messagingSenderId: '358582698343',
    projectId: 'safespace-chattingapp',
    authDomain: 'safespace-chattingapp.firebaseapp.com',
    storageBucket: 'safespace-chattingapp.firebasestorage.app',
    measurementId: 'G-4R3FBPY8Z1',
  );
}
